services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: industrial-mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
